type Query {
    alerts(match: SearchAlertInput): [Alert!]!
    alert(id: ID!): Alert
    metrics: [Metric!]!
    metric(name: String!): Metric
    metricData(metric: String!, start: Date, end: Date): [MetricData!]!
}

type Mutation {
    createUser(firstName: String, lastName: String, email: String!): User! # Will likely be removed once we integrate with nexus auth
    createMetric(name: String!, description: String!, type: metricType!): Metric!
    createMetricData(metric: ID!, value: Float!): MetricData!
    createAlert(alert: CreateAlertInput!): Alert!
}

type Alert {
    id: ID!
    message: String!
    loud: Boolean! = false
    severity: Severity!
	description: String!
	claimedBy: User
	source: String
    metric: Metric!
	dismissed: Boolean! = false
    createdAt: Date!
    updatedAt: Date!
}

type CreateAlertInput {
    message: String!
    loud: Boolean! = false
    severity: Severity! = low
    description: String!
    claimedBy: ID
    source: String
}

type SearchAlertInput {
    message: String
    loud: Boolean
    severity: Severity
    description: String
    claimedBy: ID
    source: String
}

type Metric {
    name: String!
    description: String!
    data: [MetricData!]!
    createdAt: String!
    updatedAt: String!
}

type MetricData {
    value: Float!
    metric: Metric!
    createdAt: Date!
}

type User {
    id: ID!
    firstName: String
    lastName: String
    email: String!
    claimedAlerts: [Alert!]!
    createdAt: Date!
    updatedAt: Date!
}

enum Severity {
    low
    medium
    high
}

scalar Date